// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOpTHZLVCB49MPrdJW0Ltfd9myCog3QKY',
    appId: '1:606848712333:web:3eb07304717a822feaacc4',
    messagingSenderId: '606848712333',
    projectId: 'telequest-bd874',
    authDomain: 'telequest-bd874.firebaseapp.com',
    storageBucket: 'telequest-bd874.appspot.com',
    measurementId: 'G-5HE70J4VZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMwKehForEYo8k5oA4rGY94PTHxOadx-8',
    appId: '1:606848712333:android:3ec7cfcaff88e9b8eaacc4',
    messagingSenderId: '606848712333',
    projectId: 'telequest-bd874',
    storageBucket: 'telequest-bd874.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA5A9krlmGjiqwmNYDOW2igUvnCgV77Jk',
    appId: '1:606848712333:ios:a776fa7f111754e0eaacc4',
    messagingSenderId: '606848712333',
    projectId: 'telequest-bd874',
    storageBucket: 'telequest-bd874.appspot.com',
    iosClientId: '606848712333-n8dfgnk7pupuio0p7i2foth0hv5n2q13.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA5A9krlmGjiqwmNYDOW2igUvnCgV77Jk',
    appId: '1:606848712333:ios:a776fa7f111754e0eaacc4',
    messagingSenderId: '606848712333',
    projectId: 'telequest-bd874',
    storageBucket: 'telequest-bd874.appspot.com',
    iosClientId: '606848712333-n8dfgnk7pupuio0p7i2foth0hv5n2q13.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasa',
  );
}
